openapi: 3.0.3
info:
  title: Ping API
  version: 1.0.0
  description: Une API simple qui répond "pong".
paths:
  /ping:
    get:
      summary: Vérifie si le serveur répond
      responses:
        '200':
          description: Réponse OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
