openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0
  description: API pour la gestion des utilisateurs.
paths:
  /users:
    get:
      summary: Récupère la liste des utilisateurs
      parameters:
        - name: page
          in: query
          description: Numéro de la page
          required: false
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          description: Nombre d'éléments par page
          required: false
          schema:
            type: integer
            example: 20
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Mihaja
                  email: Mihaja@gmail.com
                - id: 2
                  name: Mickael
                  email: Mickael@gmail.com
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:{"error": "Bad types for provided query parameters"}
