openapi: 3.0.3
info:
  title: API Produits
  version: "1.0.0"
paths:
  /products:
    get:
      summary: Recherche de produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        "200":
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Plusieurs produits
                  value:
                    - name: "Lait"
                      expiration_datetime: "2025-12-31T23:59:59Z"
                      price: 2.5
                    - name: "Pain"
                      expiration_datetime: "2025-09-01T23:59:59Z"
                      price: 1.0
                emptyList:
                  summary: Aucun produit
                  value: []

components:
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      example: 10
    q:
      name: q
      in: query
      required: false
      schema:
        type: string
      example: lait

  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
