openapi: 3.0.3
info:
  title: API Produits et Commandes
  version: "1.0.0"
tags:
  - name: Products
    description: Gestion des produits
  - name: Orders
    description: Gestion des commandes
paths:
  /products:
    get:
      tags:
        - Products
      summary: Liste des produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        "200":
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /orders:
    get:
      tags:
        - Orders
      summary: Liste paginée des commandes
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        "200":
          description: Liste des commandes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

    post:
      tags:
        - Orders
      summary: Crée une commande (protégé par Basic Auth)
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "201":
          description: Commande créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  parameters:
    limit:
      name: Fandresena
      in: query
      required: false
      schema:
        type: integer
      example: 10
    q:
      name: Mihaja
      in: query
      required: false
      schema:
        type: string
      example: lait
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      example: 1
    size:
      name: size
      in: query
      required: false
      schema:
        type: integer
      example: 20

  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float

  securitySchemes:
    basicAuth:
      type: http  
      scheme: basic
